In [2]:
import numpy as np

# Acessando e manipulando arrays

No notebook anterior exploramos a criação de arrays NumPy. Agora aprenderemos
como acessar e manipular elementos dentro de arrays, e também
como extrair elementos específicos deles.

## $ \S 1 $ Acessando e modificando elementos individuais de arrays

Lembre-se de que listas em Python são __mutáveis__, o que significa que podemos modificar
os elementos individuais de uma lista:

In [ ]:
primos = [199, 1_999, 19_999]
primos[2] = 19
print(primos)

Em contraste, uma tupla em Python é __imutável__. Ainda podemos acessar um
elemento usando `[]` e seu índice, mas não podemos modificar esse elemento:

In [ ]:
frutas = ('🍎', '🍊', '🍍')
print(frutas[0])

In [ ]:
frutas[0] = '🍉'

Arrays NumPy também são _mutáveis_, assim como as listas. Considere o seguinte vetor $ \boldsymbol{a} $:

In [ ]:
a = np.array([1, 2, 3])
print(a)

Para acessar ou modificar o $ 0 $-ésimo elemento de $ \boldsymbol a $ (lembre-se de que sempre
contamos a partir de $ 0 $ em Python), usamos a mesma sintaxe que usaríamos se fosse uma
lista:

In [ ]:
print(a[0])  # Acessa o 0-ésimo elemento de `a`
a[0] = -1    # Modifica este elemento
print(a)     # Imprime o resultado

Se estivermos lidando com um array $ 2D $, usamos `[i, j]` para acessar sua $ (i, j)
$-ésima entrada, ou seja, o elemento na linha $ i $ e coluna $ j $.

__Exercício:__ Modifique os elementos fora da diagonal na seguinte matriz $ A $ para
transformá-la na matriz identidade $ 2 \times 2 $.

In [ ]:
A = np.ones((2, 2))
print("Antes das modificações:")
print(A, '\n')

# ...
# ...
print("Após as modificações:")
print(A)

Em geral, ao lidar com um array $ n $-dimensional, use
`[k_1, k_2, ..., k_n]` para acessar o elemento que possui os índices
$ k_1, k_2, \cdots, k_n $, respectivamente.

__Exercício:__ Construa um array identidade $ 3D $ $ M $ de formato $ (5, 5, 5) $
preenchendo-o primeiro com zeros e depois definindo todos os elementos cujos índices
têm a forma $ (i, i, i) $ como $ 1 $ das duas maneiras a seguir: 

(a) Usando um loop `for`.

(b) Com a chamada única `fill_diagonal(M, 1)`.

In [ ]:
# Preencha M com zeros:
# M = ...

# Defina os elementos da diagonal iguais a 1:
# ...

# Imprima o resultado:
# print(M)


📝 Assim como as listas em Python, os arrays NumPy suportam indexação negativa. O índice $ -1 $
refere-se ao último elemento, $ -2 $ ao penúltimo, e assim por diante.

__Exercício:__ Modifique a última coordenada do vetor
$ \boldsymbol{v} \in \mathbb{R}^6 $ abaixo de modo que seu comprimento se torne $ 3 $. _Dica:_
Lembre-se de que a norma (comprimento) de um vetor $ \boldsymbol{v} = (v_1, v_2, \cdots, v_n) $
em $ \mathbb{R}^n $ é dada por $ \sqrt{v_1^2 + v_2^2 + \cdots + v_n^2} $.

In [ ]:
v = np.array([1, 1, 1, 1, 1, 1])

print(f"Vetor: {v}")
print(f"Norma de v = {np.linalg.norm(v):.3f}")

A indexação negativa também funciona com arrays multidimensionais:

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(A[-1, -1])  # Elemento inferior direito (valor: 9)
print(A[-2, -3])  # Elemento na penúltima linha, antepenúltima coluna (valor: 4)

__Exercício:__ Dado o array $ 3D $ abaixo, acesse e imprima:

(a) O elemento na posição $ (0, 1, 1) $.

(b) O último elemento de todo o array.

(c) O elemento na linha $ 0 $, coluna $ 1 $ da "camada" $ 2 $.

In [ ]:
B = np.array([[[1, 2], [3, 4]], 
              [[5, 6], [7, 8]], 
              [[9, 10], [11, 12]]])
print(B)
# (a)

# (b)

# (c)

## $ \S 2 $ Fatiamento de arrays $ 1D $

__Fatiamento__ (slicing) é uma operação que nos permite extrair um sub-array de um array.
A sintaxe para arrays $ 1D $ é exatamente a mesma das fatias de listas em Python,
ou seja, `a[inicio:fim:passo]`, onde `a` denota um array e:

* `inicio` é o índice onde o fatiamento começa (incluído).
* `fim` é o índice onde o fatiamento termina (excluído).
* `passo` é o tamanho do passo entre os elementos.

Se algum destes for omitido, eles assumem por padrão seus limites naturais (início do
array, fim do array e tamanho do passo $ 1 $).

__Exercício:__ Seja $ \boldsymbol a = (0, 1, \cdots, 10) $.

(a) Instancie este array usando `arange` ou com `linspace` junto com a instrução `a.astype(int)`.

(b) Faça um fatiamento de $ \boldsymbol a $ resultando em $ (0, 1, \cdots, 4) $.

(c) Fatie $ \boldsymbol a $ para obter o array $ (5, 6, \cdots, 10) $.

(d) Construa um fatiamento para recuperar o sub-array $ (3, 5, 7, 9) $.

(e) Obtenha um novo array consistindo de todos os elementos de $ \boldsymbol a $ em ordem inversa.

(f) Faça um fatiamento completo de $ \boldsymbol a $, chame-o de $ \boldsymbol b $ e modifique seu $ 0
$-ésimo elemento. $ \boldsymbol a $ é afetado?

⚠️ Como visto no exercício anterior, _fatiar um array cria apenas uma visualização (view) do
array original, não uma cópia_. Uma __visualização__ é um novo objeto de array que se refere aos
mesmos dados do array original. Isso significa que:
* Alterações feitas por meio da visualização afetam o array original e vice-versa.
* Nenhuma duplicação de memória ocorre ao criar uma visualização.

Esse comportamento é proposital, por razões de eficiência.

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]  # Isso cria uma visualização, não uma cópia

print("a original:", a)
print("Visualização b:", b)

b[0] = 8  # Modificando a visualização
print("Após modificar b, a torna-se:", a)

📝 Para criar uma cópia em vez de uma visualização no NumPy, use o método `copy()`:

In [ ]:
a = np.array([1, 2, 3, 4, 5])
c = a.copy()  # Isso cria uma cópia explícita e independente
c[1] = 8

print("Cópia c:    ", c)
print("a original:", a)  # Permanece inalterado

__Exercício:__ Crie um vetor $ \boldsymbol{a} = (1, 2, 3) $ e uma fatia completa $
\boldsymbol{b} $ de $ \boldsymbol{a} $. Verifique se $ \boldsymbol{a} $ e
$ \boldsymbol{b} $ apontam para os mesmos dados com `np.shares_memory(a, b)`.

⚠️⚡ Observe, em contraste, que fatias de listas ou tuplas em Python _são_ cópias independentes
de seus originais. No entanto, essas são cópias _rasas_: apenas
os próprios contêineres são cópias, não seus elementos. Isso pode levar a
um comportamento inesperado, como no exemplo a seguir:

In [ ]:
original = [[1, 2, 3], [4, 5, 6]]
rasa_1 = original[:]
rasa_2 = original[:]

rasa_1[0] = [-1, -2, -3]
print(original)  # original não é afetado

rasa_2[0][0] = 8
print(original)  # original é afetado!

## $ \S 3 $ Fatiamento de arrays gerais

O fatiamento se torna mais interessante com arrays de dimensões superiores. Para um array $ 2D $
, em princípio precisamos especificar fatias para ambas as dimensões, separadas por
uma vírgula. Se usarmos uma única fatia, estaremos indexando linhas inteiras.

In [ ]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(M, '\n')

# Acessando uma linha específica:
print(M[1, :], '\n')  # "Primeira" linha

In [ ]:
# Acessando uma coluna específica:
print(M[:, 2], '\n')  # "Segunda" coluna

In [ ]:
# Fatiamento de sub-array:
print(M[0:2, 1:3], '\n')  # Sub-array 2x2 superior direito

In [ ]:
# Se usarmos apenas uma fatia, então linhas inteiras são extraídas:
print(M[0:2])  # Primeiras 2 linhas

__Exercício:__ 
Dada a matriz $ 3 \times 4 $ abaixo, use fatiamento para extrair:


<img src="notebook_2_slicing.png" alt="Exercício de fatiamento" width="870" height="174">

(a) As duas primeiras linhas.

(b) As duas últimas colunas.

(c) Uma submatriz $ 2 \times 2 $ contendo os elementos na interseção das
    duas últimas linhas e das duas primeiras colunas.

In [ ]:
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
# (a)

# (b)

# (c)

Todos os princípios que vimos se estendem para arrays de dimensões superiores.

__Exercício:__ Considere um array $ 3D $ representando uma imagem RGB de formato
$ (3, \text{altura}, \text{largura}) $. Escreva fatiamentos para:

(a) Extrair apenas o canal verde (índice $ 1 $ na $ 0 $-ésima dimensão).

(b) Extrair a parte central da imagem (um retângulo com metade da altura e
    metade da largura da imagem original). _Dica:_ Use o intervalo
    $$ \texttt{[altura // 4 : (3 * altura) // 4]} $$
    para fatiar a dimensão de altura e de forma semelhante para a largura.

(c) Reduzir a amostragem da imagem pegando cada segundo pixel tanto na dimensão de altura
    quanto na de largura, como no exemplo (exagerado) abaixo.

<p align="center">
  <img src="notebook_2_panda_hi.JPG" width="40%" />
  <img src="notebook_2_panda_lo.JPG" width="40%" />
  <br>
  <em>Figura 1: Pandas em alta e baixa resolução (<a href="https://commons.wikimedia.org/wiki/File:Panda_Cub_from_Wolong,_Sichuan,_China.JPG">fonte: domínio público</a>)</em>
</p>

In [ ]:
# Vamos criar uma imagem aleatória com 3 canais (R, G e B)
# com 8 bits = 256 valores por canal (intensidades de cor entre 0 e 255):
gerador = np.random.default_rng(0)
imagem = gerador.integers(0, 256, size=(3, 1280, 720))
# (a)

# (b)

# (c)

## $ \S 4 $ Outros tipos de indexação

Vamos agora considerar alguns mecanismos adicionais de indexação que permitem
seleções e manipulações mais flexíveis de arrays.

### $ 4.1 $ Indexação com array de inteiros

A __indexação com array de inteiros__ nos permite usar uma sequência de índices para selecionar
elementos:

In [ ]:
a = np.array([0, 10, 20, 30, 40])
indices = np.array([0, 2, 3])  # Seleciona elementos nos índices 0, 2 e 3
print(a[indices])

Também podemos fornecer os índices a serem selecionados na forma de listas 
(em vez de arrays, como no exemplo anterior). Além disso, para arrays
multidimensionais, podemos selecionar combinações específicas de linhas e colunas. No
exemplo a seguir ilustramos ambos os pontos:

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Seleciona elementos da diagonal:
linhas = [0, 1, 2]  # aqui estamos usando uma _lista_ (não array) de índices
colunas = [0, 1, 2]
print(A[linhas, colunas])  # elementos da diagonal de A

Observe como os índices para as linhas e colunas são emparelhados em ordem, em vez de
serem combinados de todas as maneiras possíveis.

__Exercício:__ Para a mesma matriz $ A $ como acima, use indexação com array de inteiros para
selecionar os elementos na anti-diagonal (que vai do canto inferior esquerdo para o
canto superior direito).

In [ ]:
linhas = # ...
colunas = # ...
print(A[linhas, colunas])

__Exercício:__ Dada a matriz $ 4 \times 4 $ abaixo, use indexação com array de inteiros
para:

(a) Extrair os quatro elementos dos cantos.

(b) Extrair as entradas que são números primos.

In [ ]:
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
print(M)
# (a)

# (b)

### $ 4.2 $ Combinando diferentes tipos de índices

Podemos misturar diferentes tipos de índices (fatias, inteiros individuais, arrays) para criar
seleções mais complexas. Considere a seguinte matriz $ M $:

In [ ]:
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
print(M)

Uma alternativa é especificar uma lista dos índices nos quais queremos indexar
em algumas das dimensões. Isso nos permite capturar conjuntos de índices que não
seguem o padrão de progressão aritmética de um fatiamento.

In [ ]:
# Seleciona as linhas 0, 1 e 3, todas as colunas:
print(M[[0, 1, 3], :])

In [ ]:
# Seleciona todas as linhas, colunas 1 e 3:
print(M[:, [1, 3]])

Se em vez de usar uma fatia ou lista de índices, especificarmos um único índice para
alguma dimensão, essa dimensão "colapsa". Em particular, _o array resultante
terá um posto (rank) menor_. Isso é ilustrado pelo exemplo a seguir:

In [ ]:
# Extraindo a linha 1 através de um fatiamento duplo:
print(M[1:2, :])  # O resultado ainda é um array 2D

# Extraindo a linha 1 ao indexá-la diretamente:
print(M[1, :])  # O resultado é um array 1D

__Exercício:__ Crie um array $ 2D $ de formato $ (4, 4) $ preenchido com
números inteiros aleatórios e imprima-o para referência.

(a) Extraia a última linha para produzir um array $ 1D $.

(b) Extraia a última coluna, como um array $ 2D $.

(c) Extraia um sub-array $ 2\times 2 $ do centro deste array.

(d) Extraia o canto inferior esquerdo $ 3 \times 2 $ do array.

(e) Extraia o sub-array consistindo das colunas de índices $ 1 $ e $ 3 $
    de duas maneiras: usando uma fatia com tamanho de passo $ 2 $ e usando uma lista de
    índices.

## $ \S 5 $ Indexação booleana

### $ 5.1 $ Criando máscaras booleanas e filtrando arrays com máscaras

A __indexação booleana__ é um recurso poderoso que nos permite selecionar elementos
de um array com base em _condições_ em vez de índices.
* Primeiro criamos uma __máscara booleana__ (ou __filtro__), ou seja, um array de valores `True` e `False`
  com o mesmo formato do array original.
* Em seguida, usamos essa máscara para filtrar os elementos de nosso array onde a máscara
  é `True`.

Aqui está um exemplo onde desejamos extrair todos os componentes de um array que
são maiores que $ 2 $:

<p align="center">
  <img src="notebook_2_boolean_indexing.png" width="796" height="131">
  <br>
  <em>Figura 2: Indexação booleana</em>
</p>

In [ ]:
v = np.array([5, 1, 3, 2, 4])
print("Array original:", v)

# Cria uma máscara booleana:
mascara = v > 2
print("Filtro: ", mascara)

# Usa indexação booleana para filtrar os elementos maiores que 2:
elementos_selecionados = v[mascara]
print("Elementos selecionados:", elementos_selecionados)

📝 No NumPy, e no Python em geral, `True` é tratado como
equivalente a $ 1 $ em contextos numéricos e `False` é equivalente a
$ 0 $. Assim, no exemplo anterior, podemos calcular o número de elementos
maiores que $ 2 $ no array `v` somando as entradas da máscara
(retornaremos à função `np.sum` mais tarde):

In [ ]:
print("Nº de elementos maiores que dois:", np.sum(mascara))

A indexação booleana é particularmente útil para limpeza de dados. Também podemos filtrar
elementos em um único passo; essa sintaxe é muito comum no ecossistema NumPy,
embora possa parecer um pouco estranha no primeiro contato:

In [ ]:
u = np.array([-3, 3, -2, 2, -1, 1, 0])
resultado = u[u <= 0]
print(resultado)

__Exercício:__ Considere a matriz $ A $ dada abaixo.

(a) Extraia seus elementos que são $ \ge 2 $ usando indexação booleana.

(b) Qual é o formato da sua máscara? Qual é o formato do array resultante? Em
    qual ordem os elementos são filtrados?

In [3]:
gerador = np.random.default_rng(0)
A = gerador.integers(0, 5, size=(3, 4))
print(A)

[[4 3 2 1]
 [1 0 0 0]
 [0 4 3 4]]


📝 Ao usar indexação booleana em um array multidimensional, o resultado é
sempre um array $ 1D $ contendo os elementos onde a máscara é verdadeira.
Esse achatamento pode parecer indesejável, mas é inevitável, visto que, em geral,
o array filtrado pode conter qualquer número de elementos, e esse número
pode ser incompatível com o formato do array original.

⚠️ A indexação booleana sempre gera um novo array, mesmo quando o resultado é idêntico ao array original. Portanto, deve ser usada com cautela em dados muito grandes.

In [ ]:
v = np.array([1, 2, 3, 4, 5])
u = v[v > 0]  # Filtra os elementos de v > 0, que por acaso são todos de v

# Verificando os endereços de memória de u e v para ver se coincidem:
print(id(u))
print(id(v))

### $ 5.2 $ Combinando operações booleanas

Podemos criar máscaras mais complexas usando os operadores booleanos conhecidos
__negação__, __e__, __ou__ e __ou exclusivo__ (__xor__). No entanto, as versões
do Python para os três primeiros, `not`, `and`, `or`, respectivamente, não funcionam com
arrays booleanos. Em vez disso, devemos usar `~`, `&` e `|`, respectivamente. O
operador xor é denotado por `^`. Suas tabelas verdade são fornecidas abaixo.

<p align="center">
  <img src="notebook_2_truth_tables.png" width="752" height="168">
  <br>
  <em>Figura 3: Tabelas verdade para NOT, AND, OR e XOR</em>
</p>

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Seleciona elementos maiores que 2 E menores que 7:
print(a[(2 < a) & (a < 7)])  # Resultado: [3, 4, 5, 6]

# Seleciona elementos menores que 3 OU maiores que 7:
print(a[(a < 3) | (7 < a)])  # Resultado: [1, 2, 8, 9]

📝 Certifique-se de colocar parênteses em torno de cada condição ao combiná-las.

__Exercício:__ Dado o array abaixo, use indexação booleana para extrair:

(a) Números que sejam tanto positivos quanto pares.

(b) Números que sejam negativos ou _não_ múltiplos de $ 3 $.

(c) Números que sejam divisíveis por $ 2 $ ou $ 3 $, mas não sejam múltiplos de $ 6 $.

In [ ]:
dados = np.array([15, 23, -10, 0, 42, -7, 8, 12, -25, 30, -6, 9, -25])

# (a)

# (b)

# (c)

### $ 5.3 $ A função `where` 

A função `np.where` atende a dois propósitos principais. Quando chamada com um
único argumento como `np.where(condicao)`, o resultado consiste nos
_índices_ onde essa condição é verdadeira. 

In [ ]:
A = np.array([[1, 2, 4], 
              [5, -3, 9],
              [-7, 6, -8]])

indices_negativos = np.where(A < 0)
print("Índices dos elementos negativos:", indices_negativos)

Neste exemplo, observe que o primeiro array na tupla fornece os índices das linhas e
o segundo os índices das colunas dos elementos negativos em $ A $. Quando
emparelhamos esses índices em ordem, obtemos as coordenadas desses elementos dentro de
$ A $, por exemplo, a entrada `A[2, 0]` é $ -7 $. Se quisermos os próprios elementos
para os quais a condição se aplica, podemos usar esses índices exatamente como em $ \S 4.1 $:

In [9]:
print("Elementos negativos em A: ", A[indices_negativos])

Negative elements in A:  [-5 -7 -9]


📝 Na versão de parâmetro único do `where`, o argumento deve ser um array booleano, e o resultado
será simplesmente as posições (índices) dos elementos que são `True`.

__Exercício:__ Referindo-se à mesma matriz $ A $ como acima:

(a) Determine os índices de linha e coluna dos elementos em $ A $
que deixam resto $ 1 $ quando divididos por $ 3 $.

(b) Use os índices obtidos em (a) para construir um array consistindo dos
elementos de $ A $ que satisfazem a condição declarada.

Para ilustrar o segundo uso da função `where`, considere o seguinte array simples.

In [2]:
numeros = np.array([1, 2, -3, 4, -5, 6, -7, 8])
print(numeros)

[ 1  2 -3  4 -5  6 -7  8]


Suponha que queiramos substituir os elementos em `numeros` que são negativos por $ 0 $.
Podemos fazer isso da seguinte maneira:

In [4]:
# Substitui valores negativos por zeros, mantém valores positivos:
resultado = np.where(numeros > 0, numeros, 0)
print("Após substituir negativos por zeros:", resultado)

After replacing negatives with zeros: [1 2 0 4 0 6 0 8]


Assim, na forma `np.where(condicao, x, y)`, essa função pode funcionar como um
operador ternário vetorizado (semelhante ao `? :` em C/C++/Java ou à instrução
`... = x if condicao else y` em Python), permitindo-nos
fazer escolhas elemento a elemento entre dois arrays com base em uma condição. 

__Exercício:__ Suponha que estamos construindo um aplicativo de previsão do tempo. Precisamos
exibir as temperaturas em graus Fahrenheit ou Celsius
dependendo se o usuário está nos EUA ou não. Use `where` para realizar
isso para o seguinte conjunto de $ 10 $ temperaturas:

In [ ]:
# Array de temperaturas em Celsius:
celsius = np.array([20, 25, 30, 35, 40, 15, 10, 5, 0, -5])
# Array correspondente de temperaturas em Fahrenheit (F = C * 9/5 + 32):
# fahrenheit = ???  # calcular

# Máscara booleana que indica se o usuário é dos EUA (True) ou não (False):
visitante_eua = np.array([True, True, False, False, True, False, True, True, False, True])

# Use np.where para exibir as temperaturas nas unidades apropriadas com base na localização do visitante:
# temps_exibicao = ???

print("Temperaturas para exibir (F para EUA, C para outros):\n", np.round(temps_exibicao))