# Introdução aos arrays NumPy

## $ \S 1 $ Motivação

Um __vetor__ é uma lista ordenada de números. Suponha que desejamos representar
vetores como $ \boldsymbol{u} = (1, 2, 3) $ ou $ \boldsymbol{v} = (-1, 0, 1)
$ em Python. É natural pensar que listas ou tuplas podem ser uma boa
escolha para esta tarefa.

In [ ]:
u = [1, 2, 3]   # Cria uma lista cujos elementos são 1, 2, 3
v = [-1, 0, 1]

No entanto, em algum momento provavelmente desejaremos não apenas armazenar, mas manipular
esses vetores. Por exemplo, como podemos somar $ \boldsymbol u $ e $ \boldsymbol v $ ou
tomar um múltiplo de $ \boldsymbol v $? É razoável tentar o seguinte código:

In [ ]:
soma = u + v
multiplo = 3 * v

print(soma)
print(multiplo)

Esses resultados inesperados podem ser explicados ao lembrar que, tanto para listas quanto
para tuplas (ou strings), o operador `+` denota _concatenação_, não adição; e,
da mesma forma, `*` denota _repetição_, não multiplicação. Esse comportamento não é
nada estranho se levarmos em consideração que listas e tuplas são tipos sequenciais
_genéricos_, capazes de conter objetos de tipos arbitrários, para os quais
a adição e a multiplicação podem não fazer sentido.

__Exercício:__ O que acontece se você representar $ \boldsymbol u $ e $ \boldsymbol v $ como
tuplas e tentar obter a diferença $ \boldsymbol u - \boldsymbol v $? E se eles
forem representados como listas?

Vetores e matrizes são objetos fundamentais na engenharia, ciência
e aprendizado de máquina. Há, portanto, uma clara necessidade de uma biblioteca que
estenda o Python fornecendo maneiras eficientes de operar com esses objetos.

## $ \S 2 $ Arrays

<img src="notebook_1_NumPy.png" width="105" height="38" alt="NumPy">, que significa _Numerical Python_, é um pacote fundamental
para computação científica em Python. Ele é quase universalmente importado com o
apelido `np`, da seguinte forma:

In [ ]:
import numpy as np

Também poderíamos importar todos os objetos/funções do NumPy com:

In [ ]:
from numpy import *

Com isso, evitaríamos ter que digitar o prefixo `np.` todas as vezes. No entanto,
isso não é recomendado, pois pode levar a conflitos com nomes no Python puro
(por exemplo `max` e `min`) ou com aqueles usados por outros módulos (como
`exp` e `sqrt` do módulo Math).

O recurso central do NumPy é uma nova estrutura de dados chamada **ndarray** (uma
abreviação de array $n$-dimensional), ou simplesmente **array**. Um array é
essencialmente uma tabela multidimensional. Por exemplo, um array $ 1 $-dimensional é
outra versão de uma lista; é apenas uma linha de dados. Um array $ 2 $-dimensional pode ser
visto como uma planilha ou matriz. E arrays $ 3 $-dimensionais são pilhas de
tabelas, por exemplo, com o formato de um cubo.

Um ndarray é uma grade de valores _do mesmo tipo de dado_; em outras palavras, os arrays
devem ser **homogêneos**. Na maioria das aplicações, esse tipo de dado é numérico (por exemplo, os
elementos do array são todos inteiros sem sinal de $ 32 $ bits ou todos números de ponto
flutuante de $ 64 $ bits). No entanto, também é possível criar um array cujos
elementos sejam booleanos ou strings, por exemplo.

Um array numérico $ 1 $-dimensional é semelhante a um vetor no sentido da
Álgebra Linear, como na discussão em $ \S 1 $. Os arrays podem ser instanciados
com a função `array`:

In [ ]:
u = np.array([1, 2, 3])     # Chamando `array` na lista [1, 2, 3]
print(u)
print(f"O tipo de um array como u é: {type(u)}")

Observe a ausência de vírgulas separando os elementos do array quando ele é exibido
(em contraste com as listas).

__Exercício:__ Imprima a lista `primos = [2, 3, 5, 7]` e o seu tipo. Em seguida, gere
um array `arr_primos` a partir desta lista e imprima-o, juntamente com o seu tipo.

__Exercício:__ Defina o vetor
$ \boldsymbol a = \frac{1}{2} \big(1, 1, 1, 1 \big) \in \mathbb R^4 $ como um array NumPy.
Calcule o comprimento (norma) de $ \boldsymbol a $ à mão e compare sua resposta com
o resultado obtido por meio da função `np.linalg.norm`.

__Exercício:__ Imprima e determine os tipos dos seguintes arrays.

In [ ]:
b = np.array([True, False, True, False])
s = np.array(list("teste"))

📝 Para recapitular, `ndarray` é o nome oficial do tipo de dado fornecido pelo NumPy, e `array` é tanto
o nome informal desse tipo de dado quanto o nome da função que podemos usar
para criar ndarrays.

O argumento da função `array` pode ser uma lista, uma tupla, um `range`, outro
array ou qualquer objeto semelhante a um array.

In [ ]:
v = np.array((-1, 0, 1))    # O argumento de `array` também pode ser uma tupla
print(v)

**Exercício:**  

(a) Usando a função `range`, gere a sequência de números ímpares entre $ 1 $ e $ 9 $,
    e chame-a de `impares`.

(b) Aplique a função `array` em `impares` para gerar um array composto pelos mesmos números.

Observe que o tipo de um array como um todo é sempre o mesmo (`numpy.ndarray`)
e não deve ser confundido com o seu __tipo de dado__, que é o tipo dos
_elementos_ que ele contém. Podemos determinar o tipo de dado de um array $ \boldsymbol a $ por meio de `a.dtype`:

In [ ]:
v.dtype

Como podemos ver, o array $ \boldsymbol v = (-1, 0, 1) $ definido acima contém inteiros de $ 64 $ bits.

__Exercício:__ Determine o tipo de dado dos arrays $ \boldsymbol b $ e
$ \boldsymbol c $ definidos abaixo.

In [ ]:
b = np.array([True, False, True, False])
c = np.array((1, 2, 3.))

## $ \S 3 $ Arrays multidimensionais

O número de dimensões de um array também é chamado de seu
**posto**. Um array $ 2 $-dimensional, ou array de posto $ 2 $, pode ser visto
como uma tabela ou matriz. 

In [ ]:
A = np.array([[1, 1, 1, 1],   # primeira linha da matriz A
              [2, 2, 2, 2],   # segunda linha
              [3, 3, 3, 3]])  # terceira linha
print(A)
print(type(A))  # Imprime o tipo do objeto A

Observe o uso de colchetes _duplos_ aqui: o primeiro colchete de abertura `[` serve
para delimitar a própria matriz, enquanto o segundo é usado para delimitar os elementos
da primeira linha. As linhas são separadas por vírgulas, assim como os elementos dentro de cada linha.

📝 No código do exemplo anterior, cada linha da matriz aparece sozinha
em uma linha de texto para melhorar a legibilidade, mas os caracteres de quebra de linha não
delimitam de fato as linhas (as vírgulas e os colchetes é que fazem isso).
Portanto, o código a seguir produz o mesmo resultado:

In [ ]:
A = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]])
print(A)

__Exercício:__ Crie e exiba a matriz
$$
    T = \begin{bmatrix}
    \phantom{-}0 & \phantom{-}1 & \phantom{-}0 \\
    -1 & \phantom{-}0 & \phantom{-}1 \\
    \phantom{-}0 & -1 & \phantom{-}0
    \end{bmatrix}
$$

__Exercício:__ Crie um array $ 3\times 3 $ para representar um tabuleiro de jogo da velha.
Use a string `' '` (um único espaço em branco) para uma célula vazia, e as strings
`'X'` e `'O'` para as peças colocadas por cada um dos dois jogadores.
Configure o tabuleiro para o seguinte estado de jogo:

<p align="center">
  <img src="notebook_1_tic_tac_toe.png" width="200">
  <br>
  <em>Figura 1: Jogo da velha</em>
</p>

In [ ]:
tabuleiro_jogo = np.array(...)

print(tabuleiro_jogo)

⚡ Arrays não precisam ser retangulares; eles também podem ser
_irregulares_ (significando que as linhas podem ter comprimentos diferentes), como no exemplo
abaixo. No entanto, arrays irregulares perdem muitos dos benefícios de desempenho do NumPy, que
dependem de formatos consistentes para eficiência.

In [ ]:
irregular = np.array([
    [1, 2, 3],
    [4, 5],
    [6, 7, 8, 9]
], dtype=object)
print(irregular)

Observe que este array está armazenando listas do Python, em vez de um
bloco contíguo de memória com inteiros.

O __formato__ de um array é uma _tupla_ de inteiros indicando o tamanho de cada uma de
suas dimensões. O array $ A $ abaixo tem formato $ (3, 4) $, pois possui três
linhas e quatro colunas.

In [ ]:
A = np.array([[42, 17, 99, 3], [-2, -3, -5, -7], [0, 0, 0, 0]])
print(A)
print(A.shape)  # Imprime o formato de A

__Exercício:__ Qual é o formato de um array unidimensional, por exemplo o
array $ \boldsymbol b $ abaixo? Você consegue explicar o resultado de `b.shape` (por que existe
uma vírgula quando você o imprime)?

In [ ]:
b = np.array([True, False, False, True, False])

__Exercício:__ Como podemos instanciar a matriz
$$
\boldsymbol{B} = 
\left[ \begin{array}{ccc}
b_{11} & b_{12} & b_{13} \\
b_{21} & b_{22} & b_{23} \\
b_{31} & b_{32} & b_{33} \\
b_{41} & b_{42} & b_{43}
\end{array} \right]
$$
onde $ b_{ij} = i + j $? Digitar cada elemento manualmente seria tedioso
e propenso a erros. Em vez disso, podemos usar o procedimento `fromfunction` que
constrói um array aplicando uma função Python a cada um de seus índices.
A sintaxe básica é: `np.fromfunction(funcao, formato)`. Use isso para
construir $ B $. _Dica:_ Primeiro defina uma função (usando `def` ou `lambda`) que
mapeie $ (i, j) $ para $ i + j $.

⚡ __Exercício:__ Relembre a matriz $ \boldsymbol{B} = \big(b_{ij}\big) = (i + j) $ de
um exercício anterior. Use uma compreensão de lista dupla para gerar os $ b_{ij} $
como uma lista de listas e, em seguida, converta isso em um array. _Dica:_ Você precisará de uma
compreensão dupla, da forma `[[... for j in ...] for i in ...]`. 

Um array $ 3D $ está para uma matriz assim como um bloco sólido está para um retângulo. Em outras palavras,
um array de posto $ 3 $ é aquele que possui três eixos em vez de apenas dois.

<p align="center">
  <img src="notebook_1_array_3D.png" width="400">
  <br>
  <em>Figura 2: Representação de um array 3D</em>
</p>

__Exercício:__ Qual é o posto e o formato do array representado acima?

Aqui está um exemplo concreto de um array $ 3D $ com formato $ 2 \times 2 \times 2 $.
Pense nele como um array com $ 2 $ camadas, cada uma das quais é uma matriz $ 2 \times 2 $.

In [ ]:
# Observe que agora precisamos de três pares de colchetes:
A = np.array([[[1, 2],   # A primeira camada é uma matriz 2x2
               [3, 4]], 

              [[5, 6],   # A segunda camada também é uma matriz 2x2
               [7, 8]]])
print(A)

__Exercício:__ O que acontece se você excluir a linha em branco dentro da definição de $ A $ acima?
O que acontece se você inserir uma linha em branco adicional?

Observe que um array $ 3D $ não precisa ser um cubo (ou seja, ter todas as três dimensões
com o mesmo comprimento) como no exemplo anterior.

__Exercício:__ Construa um array de posto três com formato $ (2, 3, 4) $. 
_Dica:_ Pense nisso como um par de matrizes $ 3 \times 4 $.

Não há limite para o número de dimensões que um array pode ter. Embora
a maioria das aplicações exija apenas arrays de posto $ 1 $ e $ 2 $,
arrays de dimensões mais altas surgem naturalmente em algumas áreas. Por exemplo, em
processamento de imagem, fotos RGB podem ser vistas como arrays $ 3D $ com dimensões para
altura, largura e canais de cor (vermelho, verde, azul). Isto é, uma imagem como
a abaixo pode ser decomposta em três arrays $ 2D $, cada um representando a
intensidade de uma cor em cada pixel.

<p align="center">
  <img src="notebook_1_RGB_separation.jpg" width="200" height="600">
  <br>
  <em>Figura 3: Separação dos canais RGB. (<a href="https://commons.wikimedia.org/wiki/File:Barn_grand_tetons_rgb_separation.jpg?uselang=en#Licensing">fonte: domínio público</a>)</em>
</p>


Da mesma forma, o processamento de vídeo usa arrays $ 4D $ (tempo, canais, altura, largura)
e o aprendizado de máquina frequentemente usa arrays multidimensionais.

<p align="center">
  <img src="notebook_1_stroboscopische_scheibe.gif">
  <br>
  <em>Figura 4: Este vídeo é uma sequência ordenada de imagens coloridas, portanto pode ser codificado como um array 4D. (<a href="https://commons.wikimedia.org/wiki/File:Panda_Cub_from_Wolong,_Sichuan,_China.JPG?uselang=en#Licensing">fonte: domínio público</a>)</em>
</p>

Indo na direção oposta, um array $ 0 $-dimensional contém um único objeto,
mas ainda é um objeto `ndarray` completo. Considere o seguinte array escalar
consistindo do número $ 5 $:

In [4]:
s = np.array(5)  # observe a ausência de uma lista ou tupla
print(s)

5


Como acima, observe que quando um array $ 0D $ é impresso, não há colchetes
atuando como delimitadores, embora ele não deva ser confundido com o próprio número $ 5
$, que é um objeto `int` do Python. Além disso, o formato de um array escalar
é sempre a tupla vazia (a única tupla com zero coordenadas):

In [3]:
print(s)
print(type(s))
print(s.shape)

5
<class 'numpy.ndarray'>
()


## $ \S 4 $ Outras maneiras de criar arrays

### $ 4.1 $ Preenchendo arrays automaticamente

Existem outras maneiras de criar arrays que geralmente são mais convenientes do que o uso da função `array`. Por exemplo,
para instanciar um array do formato desejado preenchido com $ 0\text{s} $, podemos usar a função `zeros`:

In [ ]:
Z = np.zeros((2, 5))  # O argumento de `zeros` é o formato desejado
print(Z)

📝 Observe os parênteses duplos necessários nesta chamada. O par mais externo
delimita os argumentos da função `zeros` e o par mais interno
especifica o formato, que é sempre uma tupla. No entanto, há uma exceção para
arrays $ 1D $. Se quisermos um vetor com, digamos, $ 10 $ coordenadas iguais a
$ 0 $, podemos usar `np.zeros((10,))` ou `np.zeros(10)`.

In [ ]:
origem = np.zeros(3)
print(origem)

Observe que, por padrão, o array resultante tem tipo de dado de ponto flutuante.

__Exercício:__ Crie e imprima um array $ 3D $ de formato $ (3, 4, 5) $ preenchido com zeros.

Arrays também podem ser preenchidos automaticamente com $ 1\text{s} $ por meio da função `ones`: 

In [ ]:
U = np.ones((2, 3))
print(U)

Generalizando `zeros` e `ones`, a função `full` cria um array de um
formato especificado, preenchido inteiramente com um valor predeterminado:

In [ ]:
# Cria um array 3x5 onde todos os elementos são iguais a 3.14:
P = np.full((3, 5), 3.14)
print(P)

__Exercício:__ Crie um array $ 1D $ com $ 50 $ coordenadas, todas iguais a $ 1 $, de duas maneiras diferentes.

Também podemos criar um novo array com formato e tipo de dado especificados, mas sem
inicializar as entradas, por meio da função `empty`. Os valores não inicializados
são o que quer que esteja na localização de memória alocada naquele momento,
o que pode levar a resultados imprevisíveis se o array for usado sem antes
atribuir valores adequados. Por outro lado, essa abordagem pode ser mais eficiente,
pois evita o custo computacional de definir cada elemento para algum valor padrão
apenas para modificá-lo mais tarde.

In [5]:
# Cria um array não inicializado:
e = np.empty((2, 2), dtype=float)

print("Aqui está o array não inicializado:")
print(e)

# Inicializa o array com novos valores:
e.fill(5.0)    # agora cada entrada é igual a 5
e[0, 1] = e[1, 0] = 3    # definindo as entradas fora da diagonal para 3

print("\nApós a inicialização:")
print(e)

Here's the uninitialized array:
[[1.40289004e-315 0.00000000e+000]
 [1.38729293e-315 1.38728709e-315]]

After initialization:
[[5. 3.]
 [3. 5.]]


Finalmente, podemos criar um novo array _com o mesmo formato e tipo de dado_ de um
dado array $ A $, mas preenchido com zeros, uns, algum outro valor especificado ou
valores lixo não inicializados com as funções `zeros_like`, `ones_like`,
`full_like` e `empty_like`, respectivamente:

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

Z = np.zeros_like(A)
print(Z, '\n')

T = np.full_like(A, 3)
print(T)

### $ 4.2 $ Gerando sequências com `arange`

A função `arange` é muito parecida com a função nativa `range` do Python, mas retorna um array:

In [ ]:
digitos = np.arange(10)
print(type(digitos), digitos)

A sintaxe completa é `arange(<inicio>, <fim>, <passo>)`. Observe que o valor
inicial é incluído, mas o valor final não (exatamente como no `range` padrão).

In [ ]:
y = np.arange(4, 10, 2)
print(y)

Uma vantagem do `arange` sobre o `range` é que _ele aceita argumentos do tipo float_. Por exemplo:

In [ ]:
x = np.arange(0.1, 1, 0.1)
print(x)

No entanto, esse recurso deve ser usado com cautela, pois às vezes erros de arredondamento
podem levar a resultados inesperados, como no exemplo a seguir:

In [ ]:
print(np.arange(1, 1.3, 0.1))
print("Observe que o valor 1.3 foi incluído!")

__Exercício:__ Para cada item, crie um array $ 1D $ contendo os elementos descritos:

(a) A sequência de números pares entre $ 2 $ e $ 19 $.

(b) Todos os inteiros de $ 10 $ até $ 1 $ em ordem decrescente.

(c) Todos os inteiros de $ 5 $ a $ 15 $ (inclusive), mas representados como
números de ponto flutuante.


(d) Todos os números de $ -3.14 $ a $ 2.86 = -3.14 + 6 $, com um passo de $ 2 $.

### $ 4.3 $ Gerando sequências com `linspace` e `logspace`

Com `linspace`, podemos construir um array contendo valores igualmente espaçados
dentro de um intervalo especificado. A sintaxe é semelhante à do `arange`,
com a exceção de que _o valor final no segundo argumento é incluído_ no resultado, e
_o terceiro argumento fornece o número de valores a serem gerados_, em vez do
tamanho do passo:

In [ ]:
z = np.linspace(0, 10, 11)
print(z, '\n')

w = np.linspace(0, 10, 10)
print(w)

__Exercício:__ Dividindo o intervalo $ [0, 1] $ em três partes iguais, obtemos três subintervalos de comprimento $ \frac{1}{3} $. Quantos pontos de subdivisão são necessários? Use `linspace` para obtê-los.

__Exercício:__ Quantos intervalos limitados são determinados por $ n + 1 $ pontos igualmente espaçados em uma reta?

Para recapitular, a sintaxe é `linspace(<inicio>, <fim (inclusive)>, <# 
elementos>)`. Podemos excluir o valor final no `linspace` para fazê-lo se comportar
de forma mais parecida com o `arange` usando `endpoint=False`:

In [ ]:
print(np.linspace(0, 10, 10, endpoint=False))

📝 Ao usar `linspace`, podemos evitar o comportamento frequentemente perigoso do `arange` quando usado
com argumento de ponto flutuante, como em um exemplo que vimos acima, onde desejávamos
gerar um array contendo os três números $ 1.0 $, $ 1.1 $ e $ 1.2 $:

In [10]:
r = np.arange(1.0, 1.3, 0.1)  # nossa intenção era que 1.3 _não_ fosse incluído
print(r)  # mas ele foi

# Poderíamos dar ao arange uma margem para os erros de arredondamento:
r = np.arange(1.0, 1.25, 0.1)
print(r)

# Mas o linspace é muito mais confiável aqui:
l = np.linspace(1.0, 1.2, 3)
print(l)

[1.  1.1 1.2 1.3]
[1.  1.1 1.2]
[1.  1.1 1.2]


__Exercício:__ O que acontece com o resultado de `linspace` se o valor inicial for maior que o valor final? E se eles forem iguais? E se o terceiro argumento for zero ou negativo? 

A função `logspace` gera pontos que são igualmente espaçados em uma
escala _logarítmica_. Por exemplo:

In [ ]:
potencias = np.logspace(-1, 2, 4)
print(potencias)

Formalmente, `logspace(inicio, fim, num)` cria um array de valores onde cada
elemento é calculado como:
$$
    10^{\text{inicio}} \times 10^{\,i \times \frac{\text{fim}-\text{inicio}}{\text{num}-1}}
    \quad \text{para $ i = 0, 1, 2, ..., \text{num} - 1 $}\,.
$$
Mais concisamente, o logaritmo de um `logspace` é o `linspace` correspondente:
$$
    \text{logspace(inicio, fim, num)} = 10^{\text{linspace(inicio, fim, num)}}
$$

Aqui `num` é o número de elementos no array resultante. Portanto, são os
_expoentes_ dos números na sequência que estão igualmente espaçados, em vez de
os próprios números.

__Exercício:__ Crie um espaço logarítmico de $ 10^{-2} $ a $ 10^2 $ com $ 20
$ pontos. Calcule e imprima as razões entre pontos consecutivos para verificar
que elas são constantes (o que é uma propriedade do espaçamento logarítmico).

Este tipo de sequência é útil para plotar dados que seguem uma lei de potência ou
que possuem uma grande amplitude, para criar eixos de frequência em processamento de áudio,
e para definir taxas de aprendizado em algoritmos de aprendizado de máquina que exigem decaimento exponencial,
entre outras aplicações.

Embora a base padrão do `logspace` seja $ 10 $, podemos usar qualquer outra base
positiva alterando o parâmetro `base`. A base $ 2 $ é particularmente útil
em aplicações de computação.

__Exercício:__ Gere todas as potências de $ 2 $ de $ 1 = 2^0 $ a $ 2^9 = 512 $
modificando o código a seguir. Imprima o array resultante para verificar sua resposta.

In [ ]:
# potencias_de_dois = np.logspace(<inicio>, <fim>, <num>, base=2)

## $ \S 5 $ Outros recursos do NumPy

Como veremos mais adiante, os arrays são muito mais eficientes e convenientes para computação
numérica do que os tipos de dados nativos do Python, como listas, tanto em memória quanto
em custos computacionais. O NumPy é usado em análise de dados, aprendizado de máquina,
engenharia e qualquer outro campo que exija computação
numérica intensiva. Ele também serve como base para bibliotecas de nível mais alto,
como SciPy, pandas e scikit-learn. Outros recursos
fornecidos pelo NumPy incluem (mas não se limitam a):
* Operações estatísticas básicas;
* Geração de números aleatórios a partir de várias distribuições de probabilidade;
* Transformadas de Fourier e processamento de sinais;
* Integração com diversos tipos de bancos de dados e formatos de arquivo para importação/exportação de dados.

Encontraremos e usaremos alguns desses recursos em outros notebooks.

⚡️ __Exercício:__ Crie uma função `diamante` que retorne um array bidimensional
de inteiros cujos uns formam a forma de um diamante, como nos seguintes exemplos:

In [ ]:
print(diamante(0))
# Deve imprimir:
# [[1]]

In [ ]:
print(diamante(1))
# Deve imprimir:
# [[0 1 0]
#  [1 0 1]
#  [0 1 0]]

In [ ]:
print(diamante(2))
# Deve imprimir:
# [[0 0 1 0 0]
#  [0 1 0 1 0]
#  [1 0 0 0 1]
#  [0 1 0 1 0]
#  [0 0 1 0 0]]

_Dica:_ Observe que, para cada elemento igual a $ 1 $, a soma das distâncias até
a linha central e a coluna central é constante.

In [ ]:
def diamante(n):
    """ Crie um array 2D de formato (2n + 1, 2n + 1)
    com entradas iguais a 1 formando a forma de um diamante. """