In [6]:
import numpy as np

# Álgebra Linear com NumPy

Nos notebooks anteriores, exploramos arrays NumPy e suas operações básicas.
Aqui, vamos nos concentrar nos comandos básicos do NumPy para fazer Álgebra Linear, que é
talvez ainda mais importante que o Cálculo para muitas aplicações de engenharia,
como análise estrutural, processamento de sinais, otimização e análise de
circuitos, entre outros. Também é essencial para aprendizado de máquina e computação gráfica.

## $ \S 1 $ Operações básicas com vetores

### $ 1.1 $ Adição de vetores e multiplicação por escalar

Vimos no notebook anterior que um vetor como $ (1, 2, 3) $
pode ser representado no NumPy como um array $ 1D $:

In [ ]:
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

Também podemos usar o NumPy para realizar todas as operações familiares com vetores.

Dados os vetores $ \mathbf v = (v_1, v_2, \cdots, v_n) $ e $ \mathbf w = (w_1,
w_2, \cdots, w_n) $ com o mesmo número de coordenadas, sua __soma__ e
__diferença__ são calculadas elemento a elemento:
$$
\begin{alignat*}{2}
\mathbf{v} + \mathbf{w} &= (v_1 + w_1, v_2 + w_2, \ldots, v_n + w_n) \\
\mathbf{v} - \mathbf{w} &= (v_1 - w_1, v_2 - w_2, \ldots, v_n - w_n)
\end{alignat*}
$$
O NumPy usa a mesma notação:

In [ ]:
s = v + w
print(s, type(s))

d = v - w
print(d, type(d))

__Multiplicação por escalar__ de um vetor por um fator $ c \in \mathbb{R} $ também é definida
elemento a elemento:
$$
c\, \mathbf v = (c\,v_1, c\,v_2, \cdots, c\,v_n)\,.
$$

In [ ]:
print(2 * v)
print(-3.14 * v)
print(0 * v)

Naturalmente, também podemos escrever $ -\mathbf v $ em vez de $ (-1)\mathbf v $. Tente no bloco de código abaixo:

Se operarmos em um array cujo tipo de dados é `int` e qualquer número de ponto flutuante está
envolvido na operação, então o resultado será do tipo de dados `float`. Uma observação
semelhante se aplica a qualquer outra coerção de tipo.

In [ ]:
# `v.dtype` retorna o tipo de dados dos elementos de v.
# Estudaremos `dtype` com mais detalhes posteriormente.
v = np.array([1, 2, 3])
print(v, v.dtype)

u = 1.0 * v
print(u, u.dtype)

__Exercício:__ Você consegue explicar a saída da célula seguinte?

In [ ]:
x = np.array([-1, 0, 1, 3])
b = np.array([True, False, True, False])

x_plus_b = x + b
print(x_plus_b, x_plus_b.dtype)

### $ 1.2 $ Produtos escalares

O __produto escalar__ $ \mathbf v \cdot \mathbf w $ de dois vetores $ \mathbf v =
(w_1, w_2, \cdots, w_n) $ e $ \mathbf w  = (w_1, w_2, \cdots, w_n) $ do
mesmo formato é a soma dos produtos de suas coordenadas correspondentes:
$$
\boxed{\ \mathbf v \cdot \mathbf w = \sum_{i=1}^n v_i\,w_i =  v_1w_1 + v_2w_2 + \cdots + v_nw_n\ } 
$$
A função `dot` calcula produtos escalares:

In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 0, -1])

dot_product = np.dot(a, b)
print(dot_product)

Equivalentemente, também podemos usar o operador `@`:

In [ ]:
alternative_dot_product = a @ b
print(alternative_dot_product)

__Exercício:__ Calcule o produto escalar de $ \mathbf{v} = (2, 3, -1) $ e
$ \mathbf{w} = (4, 0, 5) $ usando `dot` e `@`.

É fácil verificar diretamente da definição que o produto escalar é:
* simétrico, ou seja,
    $$ \mathbf v \cdot \mathbf w = \mathbf w \cdot \mathbf v $$
* bilinear, significando que 
\begin{alignat*}{9}
    (a\, \mathbf u + b\,\mathbf v) \cdot \mathbf w
    &= a\, (\mathbf u \cdot \mathbf w) + b\, (\mathbf v \cdot \mathbf w) \\
    \mathbf u \cdot (a\,\mathbf v + b\,\mathbf w) 
    &= a\, (\mathbf u \cdot \mathbf v) + b\, (\mathbf u \cdot \mathbf w)\,.
\end{alignat*}

Aqui $ \mathbf u,\,\mathbf v,\, \mathbf w \in \mathbb R^n $ e $ a,\,b \in \mathbb R\, $ são arbitrários.

### $ 1.3 $ Norma de vetores

A __norma__ ou __comprimento__ de um vetor
$ \mathbf v = (v_1, v_2, \cdots, v_n) \in \mathbb R^n $ é definida por
$$
\boxed{\ \Vert \mathbf v \Vert = \sqrt{\mathbf v \cdot \mathbf v} = \sqrt{v_1^2 + v_2^2 + \cdots + v_n^2}\ } $$
Na dimensão $ 2 $, esta definição de "comprimento" corresponde à nossa noção intuitiva e
pode ser justificada por uma simples aplicação do teorema de Pitágoras, como ilustrado
na figura abaixo. 

<img src="notebook_3_vector.png" alt="Vector" width="500px">

Em dimensões mais altas, poderíamos derivar de forma semelhante a fórmula para o comprimento usando
o teorema de Pitágoras e indução. Por exemplo, a norma (comprimento) do vetor
$ \mathbf w = (1, -2, 3) \in \mathbb R^3 $ é
$ \Vert \mathbf{w} \Vert = \sqrt{1^2 + (-2)^2 + 3^2} = \sqrt{14} $.


No NumPy, a norma de um vetor pode ser facilmente calculada com uma chamada à
função `norm` do submódulo `linalg`:

In [ ]:
v = np.array([3, 4])

print(np.linalg.norm(v))

# Alternativamente, podemos tirar a raiz quadrada do produto escalar:
print(np.sqrt(v @ v))

__Exercício:__ Verifique com a ajuda do NumPy que o comprimento de
$ \mathbf{u} = \big(\frac{1}{2}, \frac{1}{2}, \frac{1}{2}, \frac{1}{2} \big) \in \mathbb R^4 $
é $ 1 $.

⚡ Também podemos usar `norm` para calcular diferentes normas, por exemplo:
$$
\begin{alignat*}{2}
    \|\mathbf{v}\|_1 &= \sum_{i=1}^n |v_i| &\quad& \text{(norma $ L_1 $ para $\mathbf{v} \in \mathbb{R}^n$)} \\
    \|\mathbf{v}\|_{\infty} &= \max_{1 \leq i \leq n} |v_i| && \text{(norma $ L_\infty$ para $\mathbf{v} \in \mathbb{R}^n$)}
\end{alignat*}
$$
Nesta notação, a norma usual (Euclidiana) também é chamada de norma $ L_2 $.

__Exercício:__ Seja
$ \mathbf{u} = \big(\frac{1}{2}, \frac{1}{2}, \frac{1}{2}, \frac{1}{2} \big) \in \mathbb R^4 $.
Calcule suas normas $ L_1 $ e $ L_\infty $ fornecendo os argumentos adicionais
`ord=1` e `ord=np.inf` para a função `norm`.

In [ ]:
norm_u_1 = # ...    # Norma L_1 (distância de Manhattan)
norm_u_inf = # ...    # Norma L_infinito (valor absoluto máximo)

print(f"Norma L_1 de u = {norm_u_1}")
print(f"Norma L_infinito de u = {norm_u_inf}")

### $ 1.4 $ A geometria dos produtos escalares

Lembre-se que dois vetores são __ortogonais__ (ou __perpendiculares__) se e somente se
seu produto escalar é zero. 

__Exercício:__ Determine se os dois vetores abaixo são ortogonais
calculando seu produto escalar:

In [ ]:
a = np.array([-3, 4, 7, 3, -6])
b = np.array([2, 5, -2, 4, 2])

De forma mais geral, lembre-se da Álgebra Linear a seguinte relação entre o produto escalar e
o menor ângulo $ \theta \in [0, \pi] $ entre dois vetores não nulos:
$$
\boxed{\ \cos \theta = \frac{\mathbf v \cdot \mathbf w}{\Vert \mathbf v \Vert \,\Vert \mathbf w \Vert}\ }
$$
                                                                                                    

__Exercício:__ Calcule o ângulo entre os vetores $ \mathbf v = (2, 0) $ e
$ \mathbf w = (3, 3) $ em graus. Verifique sua resposta com a figura abaixo.
_Dica:_ Use `np.arccos` para calcular o arco cosseno e `np.degrees` para transformar
o resultado em graus.


<img src="notebook_3_vectors_and_angle.png" alt="Angle" width="500px">

__Exercício:__ Considere os vetores $ \mathbf a $ e $ \mathbf b $ na 
figura abaixo. Projete $ \mathbf b $ ortogonalmente na linha gerada
por $ \mathbf a $. Ou seja, calcule a projeção
$$ \boxed{\ \mathbf p = \frac{\mathbf b \cdot \mathbf a}{\Vert \mathbf{a} \Vert^2}\, \mathbf a
= \frac{\mathbf b \cdot \mathbf a}{\mathbf a \cdot \mathbf a}\, \mathbf a\ } $$

<img src="notebook_3_projection.png" alt="Projection" width="400px">

In [ ]:
# a = ...
# b = ...
# p = ...
print(p)

Um __vetor unitário__ é um vetor de comprimento $ 1 $. Para obter um vetor unitário $ \mathbf u $ tendo a mesma
direção que um dado vetor não nulo $ \mathbf v $, podemos simplesmente dividir este último por sua norma:
$$
    \mathbf u = \frac{\mathbf v}{\Vert \mathbf v \Vert}\,.
$$
De fato, usando as propriedades do produto escalar e a definição da norma, podemos verificar diretamente que
$$
    \mathbf u \cdot \mathbf u = \bigg(\frac{\mathbf v}{\Vert \mathbf v \Vert}\bigg) \cdot \bigg(\frac{\mathbf v}{\Vert \mathbf v \Vert}\bigg)
    = \frac{{\mathbf v \cdot \mathbf v}}{\Vert \mathbf v \Vert^2} = 1\,.
$$

__Exercício:__ Quantos vetores _unitários_ em $ \mathbb{R}^3 $ são paralelos a $ \mathbf v = (3, -4, 12) $ (ou seja, estão na mesma linha que passa pela origem como $ \mathbf v $)? Calcule todos eles usando NumPy.

In [ ]:
v = np.array([3, -4, 12])

__Exercício:__ A __base canônica__ em $ \mathbb R^3 $ consiste nos três vetores
$$ \mathbf e_1 = (1, 0, 0)\,, \quad \mathbf e_2 = (0, 1, 0)\,, \quad \text{e} \quad \mathbf e_3 = (0, 0, 1) \,,$$
que têm norma $ 1 $ e apontam na mesma direção que os eixos positivos $ x $, $ y $ e $ z$, respectivamente.
Calcule todos os produtos escalares possíveis $ \mathbf e_i \cdot \mathbf e_j $.
Armazene os produtos escalares em uma matriz $ 3 \times 3 $ cuja entrada $ (i, j) $
é igual a $ \mathbf{e}_i \cdot \mathbf{e}_j $.
 _Dica:_ Armazene os vetores em uma lista e use dois loops for. 

### $ 1.5 $ O produto vetorial

O __produto vetorial__ $ \mathbf v \times \mathbf w \in \mathbb R^3 $ de dois vetores _no
espaço tridimensional_ resulta em um vetor que:
1. é ortogonal a $ \mathbf v $ e $ \mathbf w $;
2. tem comprimento dado por
$$
\boxed{\ \Vert{\mathbf v \times \mathbf w}\Vert = \Vert{\mathbf v}\Vert\,\Vert{\mathbf w}\Vert\,\sin \theta\ }
$$
onde novamente $ \theta \in [0, \pi] $ denota o menor ângulo entre
$ \mathbf v $ e $ \mathbf w $. Note que a expressão à direita
coincide com a área do paralelogramo definido por $ \mathbf{v} $ e $
\mathbf{w} $.

O produto vetorial é unicamente determinado por essas duas propriedades junto com
o fato de que:

3. a base $ \big(\mathbf v,\, \mathbf w,\, \mathbf v \times \mathbf w \big) $ é _positivamente orientada_ (ou seja, este
trio de vetores, nesta ordem, satisfaz a "regra da mão direita").


<img src="notebook_3_cross_product.png" alt="Projection" width="500px">

Como o produto escalar, o produto vetorial $ \times $ também é bilinear, mas é
antissimétrico em vez de simétrico:
$$ \mathbf w \times \mathbf v = -\mathbf v \times \mathbf w \quad (\mathbf v,\, \mathbf w \in \mathbb R^3)\,.
$$
Produtos vetoriais podem ser calculados no NumPy com a função `cross`.

__Exercício:__ Sejam $ \mathbf{a} = (2, 1, 0) $ e $ \mathbf{b} = (1, 2, 0) $. Use
`cross` para verificar que:

(a) $ \mathbf{a} \times \mathbf{b} = (0, 0, 3) $.

(b) $ \mathbf{b} \times \mathbf{a} = - \mathbf{a} \times \mathbf{b} $.

## $ \S 2 $ Operações básicas envolvendo matrizes

### $ 2.1 $ Adição, subtração e multiplicação por escalar

Lembre-se que matrizes são representadas no NumPy como arrays $ 2D $. Assim como para
vetores, podemos __adicionar__ e __subtrair__ duas matrizes, ou mais genericamente quaisquer dois
arrays tendo o mesmo formato, usando `+` e `-` respectivamente.
A adição e subtração de matrizes são realizadas elemento a elemento: se $ A = (a_{ij}) $
e $ B = (b_{ij}) $, então
$$
\begin{align*}
A + B &= (a_{ij} + b_{ij}) \\
A - B &= (a_{ij} - b_{ij})
\end{align*}
$$

__Exercício:__ Calcule a soma e diferença das matrizes $ A $ e $ B $
dadas abaixo:

In [ ]:
A = np.array([[1, 2, 3],
              [1, 2, 3]])

B = np.array([[4, 4, 4],
              [5, 5, 5]])

# S = ... (soma)
# D = ... (diferença)

print("Matriz A:\n", A, '\n')
print("Matriz B:\n", B, '\n')
print("Soma:\n", S, '\n')
print("Diferença:\n", D, '\n')

Da mesma forma, para __escalar__ cada elemento de uma matriz (ou, mais genericamente, um array
$n$-dimensional) $ A $ por um escalar $ c $, podemos usar `c * A` ou `A * c`.

__Exercício:__  Calcule $ 2M $ multiplicando $ M $ por $ 2 $ tanto à direita
quanto à esquerda, onde:

In [ ]:
M = np.array([
    [4, 7, 2],
    [9, 1, 5]
])
c = 2

# print("cM:\n", ... )
# print("Mc:\n", ... )

### $ 2.2 $ Multiplicação de matrizes


A __multiplicação de matrizes__ é a operação mais fundamental na álgebra linear.
Dadas as matrizes $ A $ de formato $ (m, n) $ e $ B $ de formato $ (n, p) $, seu
produto $ C = A B $ é uma matriz de formato $ (m, p) $. A entrada $ (i, j) $ de
$ C $, denotada por $ C_{ij} $, é o produto escalar da $ i $-ésima linha de $ A $ e da
$ j $-ésima coluna de $ B $:
$$
\boxed{\ C_{ij} = (\textbf{$ \mathbf{i} $-ésima linha de $ \mathbf{A} $}) \cdot (\textbf{$ \mathbf{j} $-ésima coluna de $ \mathbf{B} $})
= \sum_{k=1}^{n} A_{ik} B_{kj}\ }
$$
Em particular, para que o produto de duas matrizes faça sentido, o número de
colunas na primeira matriz deve coincidir com o número de linhas na segunda matriz.
A multiplicação de matrizes não deve ser confundida com a multiplicação elemento a elemento,
que é menos frequentemente necessária na Álgebra Linear.

No NumPy, a multiplicação de matrizes pode ser realizada usando as funções `matmul` ou
`dot`, ou o operador `@`. 

__Exercício:__ Calcule o produto $ AB $ das matrizes $ A $ e $ B $
abaixo usando esses três métodos e compare os resultados.

In [ ]:
# Criando uma matriz 2 x 3 A:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Criando uma matriz 3 x 4 B:
B = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14],
              [15, 16, 17, 18]])

# P_1 =      (usando np.matmul())
# P_2 =      (usando np.dot())
# P_3 =      (usando o operador @)

print(P_1, '\n')
print(P_2, '\n')
print(P_3, '\n')
print(P_1.shape)

📝 Para multiplicação de matrizes, `dot`, `matmul` e `@` são completamente equivalentes
em sua saída e desempenho. A escolha entre eles é uma questão de
preferência e legibilidade do código.

Ao multiplicar um array $ 2D $ (matriz) por um array $ 1D $ (vetor), o vetor
é temporariamente visto como uma matriz coluna e a operação é tratada como uma
multiplicação de matrizes. Assim, a multiplicação matriz-vetor também pode ser tratada
por `@`, `dot` ou `matmul`.

__Exercício:__ Calcule o produto $ A \mathbf{v} $ para $ A $ e $ \mathbf{v} $
como dados abaixo usando esses três métodos. Determine o formato do resultado;
é um array $ 1D $ ou um array $ 2D $ com apenas uma coluna?

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([-1, 0, 1])


⚠️ É um erro comum para programadores usar o operador `*` quando
a multiplicação de matrizes é pretendida. No entanto, `A * B` fornece o
_produto elemento a elemento de $ A $ e $ B $._

__Exercício:__ Calcule `C @ C`, `C * C`, `C**2` e `C**(-1)` para a matriz $ C $ abaixo. Você consegue explicar esses resultados?

In [ ]:
C = np.array([[1.0, 1.0, 1.0],
              [2.0, 2.0, 2.0],
              [-3., -3., -3.]])

⚠️ A multiplicação de matrizes não é comutativa: $ A B \neq B A $ em geral.

__Exercício:__ Sejam 
$$
    P = \begin{bmatrix} 2 & 0 \\ -1 & 3 \end{bmatrix} \quad \text{e} \quad 
    Q = \begin{bmatrix} 1 & 4 \\ 2 & -3 \end{bmatrix}
$$
Verifique se $ P Q = Q P $.

__Exercício:__ Para números reais $ a,\, b $, se $ a $ e $ b $ são ambos não nulos,
então seu produto $ ab $ também é não nulo. Isso também é verdade para matrizes? _Dica:_ Tente
encontrar uma matriz $ 2 \times 2 $ não nula $ A $ tal que $ A^2 $ seja a matriz nula $ 2
\times 2 $.

Para calcular a $ n $-ésima potência de uma matriz $ A $, podemos usar `np.linalg.matrix_power(A, n)`.
Como aplicação, considere o grafo direcionado abaixo:

<img src="notebook_3_graph.png" alt="Directed graph" width="300px">

A __matriz de adjacência__  $ A $ para este grafo é uma matriz $ 4 \times 4 $ 
cuja entrada $ (i, j) $ é igual a $ 1 $ se houver uma aresta do vértice $ i $ para
o vértice $ j $ e $ 0 $ caso contrário. (Começamos a contar $ i $ e $ j $ a partir de $ 0 $
para ser consistente com nosso código.) Assim, em nosso caso:
$$
A = \begin{bmatrix}
0 & 1 & 1 & 0 \\
0 & 0 & 1 & 0 \\
1 & 0 & 0 & 1 \\
0 & 1 & 0 & 0
\end{bmatrix}
$$

As potências de uma matriz de adjacência têm uma bela interpretação na teoria dos grafos:
* $ A^1 = A $, a própria matriz de adjacência, mostra conexões diretas entre nós;
* $ A^2 $ mostra o número de caminhos de comprimento $ 2 $ entre nós;
* $ A^3 $ mostra o número de caminhos de comprimento $ 3 $ entre nós; e assim por diante...
* Em geral, $ A^n_{ij} $ representa o número de caminhos distintos de comprimento $ n $
  do vértice $ i $ para o vértice $ j $ no grafo.

No caso do nosso grafo,
$$
A^2 = \begin{bmatrix}
0 & 0 & 1 & 1 \\
1 & 0 & 0 & 1 \\
0 & 2 & 1 & 0 \\
0 & 0 & 1 & 0
\end{bmatrix}
$$
Por exemplo, o fato de que $ A^2_{2,1} = 2 $ indica que existem exatamente
dois caminhos distintos de comprimento $ 2 $ do vértice $ 2 $ para o vértice $ 1 $. De fato,
podemos verificar diretamente olhando para o grafo que esses caminhos são:
$$
2 \rightarrow 0 \rightarrow 1 \qquad \text{e} \qquad 2 \rightarrow 3 \rightarrow 1\,.
$$

__Exercício:__ Usando `np.linalg.matrix_power(A, n)`:

(a) Determine o número de caminhos de comprimento $ 20 $ que começam no vértice $ 3 $ e
terminam no vértice $ 0 $ no grafo representado acima.

(b) Determine o número de caminhos de comprimento $ \le 20 $ que começam no vértice $ 1 $
    e retornam a esse mesmo vértice. _Dica:_ Use um loop for para adicionar as entradas relevantes
    em $ I + A + A^2 + \cdots + A^{20} $.

In [ ]:
A = np.array([
    [0, 1, 1, 0],
    [0, 0, 1, 0],
    [1, 0, 0, 1],
    [0, 1, 0, 0]
])

### $ 2.3 $ Matrizes identidade e diagonais

Para instanciar uma cópia da matriz identidade de formato $ n \times n $,
podemos usar a função `identity` da seguinte forma:

In [ ]:
n = 4
I = np.identity(n)  # Criar uma matriz identidade n x n
print(I)
print(I.dtype)

Uma versão mais flexível de `identity` que permite a criação de matrizes não quadradas
é `eye` (o nome vem da letra 'I'):

In [ ]:
I = np.eye(3, 4)
print(I)

O terceiro parâmetro (opcional) de `eye` especifica um deslocamento da diagonal:

In [ ]:
I = np.eye(4, 4, 0)   # Um deslocamento de 0 corresponde à diagonal principal
U = np.eye(4, 4, 1)   # Um deslocamento de 1 corresponde à diagonal imediatamente acima da principal
L = np.eye(4, 4, -2)  # Um deslocamento negativo refere-se a uma diagonal inferior

print(I, '\n')
print(U, '\n')
print(L, '\n')

__Exercício:__ Calcule a combinação linear $ M^2 - 3 M + 2I $, para $ M $ a matriz abaixo:

In [ ]:
M = np.array([[ 0, -2],
              [ 1,  3]])

A função `diag` tem duplo propósito: ela tanto cria matrizes diagonais quanto
extrai diagonais de matrizes existentes, dependendo de sua entrada.

In [ ]:
# np.diag cria uma matriz diagonal quando recebe um array 1D:
diagonal_values = [1, 2, 3, 4]
diag_matrix = np.diag(diagonal_values)
print(diag_matrix)

In [ ]:
# np.diag extrai a diagonal quando recebe um array 2D:
existing_matrix = np.array([[1, 2, 3], 
                            [4, 5, 6], 
                            [7, 8, 9]])
diagonal = np.diag(existing_matrix)
print(diagonal, diagonal.shape)

__Exercício:__ Extraia os elementos diagonais da matriz $ C $ abaixo em um vetor e
depois calcule seu comprimento e o ângulo que ele faz com o vetor $ (7, -2, 1) $:

In [ ]:
C = np.array([[0, -4, 2],
              [3, 1, -5],
              [-3, 0, 2]])

### $ 2.4 $ Transposição

A transposta de uma matriz $ A $ é uma nova matriz $ A^T $ cujas linhas são as
colunas de $ A $ e vice-versa. Formalmente, se $ A $ é uma matriz $ m \times n $,
então $ A^T $ é uma matriz $ n \times m $ com elementos $ (A^T)_{ij} = A_{ji} $.
No NumPy, a transposta de $ A $ é denotada por `A.T`:

In [5]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("A:")
print(A, "\n")
print("A^T:")
print(A.T)

A:
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

A^T:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


__Exercício:__ Uma matriz quadrada $ n \times n $ $ A $ é
__ortogonal__ se e somente se seus $ n $ vetores coluna
$ \mathbf v_1, \cdots, \mathbf v_n $ formam uma _base ortonormal_ de $ \mathbb R^n $, ou seja,
$$
\mathbf v_i \cdot \mathbf v_j = 
\begin{cases}
1 & \text{se $ i = j $} \\
0 & \text{caso contrário}
\end{cases}
\qquad \text{para cada $ i,\,j = 1, \cdots, n\,. $}
$$

(a) Escreva um procedimento `is_orthogonal` que determina se uma
dada matriz quadrada $ n \times n $ $ A $ é ortogonal. 
_Dica:_ Use o slice `A[:, i]` para extrair o $ i $-ésimo vetor coluna de $ A $
e calcule todos os produtos escalares possíveis.

(b) Você consegue ver algum problema potencial com sua abordagem quando $ A $
consiste de números de ponto flutuante?

__Exercício:__ Uma condição equivalente para a ortogonalidade de $ A $ é que ela satisfaça
$$
A^TA = I_n = AA^T\,,
$$
onde $ A^T $ é a transposta de $ A $ e $ I_n $ é a matriz identidade $ n \times n $.
(Na verdade, qualquer uma dessas equações por si só já é suficiente para a ortogonalidade.)
 
Escreva outra versão de `is_orthogonal` que faz uso desse critério e da
transposta `A.T`. Ao comparar com a identidade, você pode querer usar
`np.round(B, 10)` para arredondar todas as entradas de $ B $ para dez dígitos decimais para evitar
falsos negativos.

### $ 2.5 $ O traço, determinante e inversa de uma matriz quadrada

Lembre-se que o __traço__ de uma matriz quadrada é, por definição, a soma de todos os
seus elementos diagonais. Para calcular o __traço__, __determinante__ e a
__inversa__ de uma matriz _quadrada_, podemos usar as funções `np.trace`, `np.linalg.det` e
`np.linalg.inv`, respectivamente. 

__Exercício:__ Calcule o traço, determinante e inversa $ X^{-1} $ de $ X $.
Verifique se $ X^{-1} X = I_2 = XX^{-1} $ e explique os resultados.

In [ ]:
X = np.array([[3, 1, 2],
              [1, 5, 1],
              [2, 1, 4]])

# trace = ...
# determinante = ...
# inversa = ...
print(f"Traço de X: {trace:.4f}")
print(f"Determinante de X: {determinante:.2f}")
print(f"Inversa de X\n: {inversa}")

__Exercício:__ Encontre a área do paralelogramo definido pelos vetores 
$ (3, 5) $ e $ (2, 4) $ em $ \mathbb{R}^2 $. Lembre-se que esta área pode ser
calculada como o valor absoluto do determinante da matriz formada por esses
vetores. _Dica:_ A função de valor absoluto no NumPy é denotada por `np.abs`.

__Exercício:__ Dadas duas matrizes quadradas $ C $ e $ D $ do mesmo tamanho, lembre-se
que o determinante do produto delas é o produto de seus determinantes:
$$
\boxed{\ \det(CD) = \det(C) \cdot \det(D)\ }
$$
Verifique esta identidade no exemplo particular onde
$$
C = \begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix} \quad \text{e} \quad
D = \begin{bmatrix}
2 & 3 \\
1 & 4 \\
\end{bmatrix}\,.
$$
$ CD = DC $?

__Exercício:__ Resolva o sistema linear de equações dado por
$ A\mathbf{x} = \mathbf{b} $, onde
$$
A = \begin{bmatrix}
1 & 2 & 3 \\
0 & 1 & 4 \\
5 & 6 & 0 \\
\end{bmatrix} \quad \text{e} \quad \mathbf b = \begin{bmatrix}
3 \\
7 \\
8 \\
\end{bmatrix}\,.
$$
Verifique sua resposta multiplicando $ A $ por $ \mathbf x $.
_Dica:_ Use a inversa de $ A $ para encontrar $ \mathbf{x} = A^{-1}\mathbf{b} $.

⚡ __Exercício:__ Para uma lista de valores $ x_0, x_1, \ldots, x_n $, a correspondente __matriz de Vandermonde
__ é definida como:
$$
V = \begin{bmatrix} 
1 & x_0 & x_0^2 & \cdots & x_0^{n} \\ 
1 & x_1 & x_1^2 & \cdots & x_1^{n} \\ 
\vdots & \vdots & \vdots & \ddots & \vdots \\ 
1 & x_n & x_n^2 & \cdots & x_n^{n}
\end{bmatrix}\,.
$$
Esta matriz surge naturalmente em problemas envolvendo interpolação polinomial e
equações diferenciais. O determinante de $ V $ tem uma bela expressão fechada:
$$
    \det(V) = \prod_{0 \leq i < j \leq n} (x_j - x_i)\,.
$$
Este é o produto de todas as diferenças possíveis entre 
dois valores, com o primeiro tendo o índice maior.

(a) Escreva um procedimento que cria uma matriz de Vandermonde para uma dada lista de
valores de entrada. _Dica:_ Comece com uma matriz nula de dimensões apropriadas e
preencha os elementos um por um. Use um loop duplo for e a fórmula $ V_{ij}
= x_i^j $.

(b) Escreva um procedimento que usa a fórmula fechada acima para calcular o
determinante da matriz de Vandermonde correspondente a uma lista de valores.
_Dica:_ Comece com o valor $ 1 $ para o determinante e use um loop duplo for
para incluir um fator $ (x_j - x_i) $ de cada vez.

(c) Teste suas funções na matriz abaixo. _Dica:_ Use `det` para verificar o
determinante que seu procedimento do item (a) produz.
$$
V = V(2, 3, 5, 7, 11) = \begin{bmatrix} 
1 & 2 & 4 & 8 & 16 \\ 
1 & 3 & 9 & 27 & 81 \\ 
1 & 5 & 25 & 125 & 625 \\ 
1 & 7 & 49 & 343 & 2401 \\ 
1 & 11 & 121 & 1331 & 14641
\end{bmatrix}
$$